# Generated by Django 5.1.1 on 2024-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5),
        ),
    ]
