# Generated by Django 5.1.1 on 2024-09-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_frame_for_completion',
            field=models.DateField(),
        ),
    ]
