# Generated by Django 5.1.1 on 2024-10-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_membership_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[('1', 'Team Member'), ('2', 'Team Lead')]),
        ),
    ]
