# Generated by Django 5.1.1 on 2024-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Team Member', 'Team Member'), ('Team Lead', 'Team Lead')], default='Team Member', max_length=20),
        ),
    ]
