# Generated by Django 5.1.1 on 2024-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboards', '0003_alter_message_topic_alter_thread_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thread',
            name='message_text',
            field=models.TextField(),
        ),
    ]
